### ISSUE TITLE
Improve paper from supervisor feedback (tracking issue)

### ISSUE THREAD

**Issue by EwoutH** [EwoutH/urban-self-driving-effects#12]
Improve the paper using the feedback from the greenlight meeting with my supervisors. This issue writes them up in actionable items and tracks them.

Gist: Focus on motivating decisions, making them explicit and making the main text fully readable on it's own.

### 1. Introduction
- [x] f299383 Briefly introduce each paper from the discussion in the introduction, building up to my research gap / novelty. At most a few sentences for each paper, really focusing on how they differ from my research (limitation, methods, etc.)
- [x] 4732e0d Change research question to reflect uncertainty (from "will" to "might")
- [x] 24743ed Add structured reading guide: brief overview of each section and how they connect to research questions

### 2. Methods
- [x] eeb35df Structure by subquestions
   * Focus on how each subquestion answered (using which methods)
- [x] a2b8c1b Add new / update content explaining:
  * Why agent-based modeling was chosen over alternatives
  * Why mesoscopic traffic modelling was chosen
  * Why a rational, VoT based choice model was chosen

### 3. Model description
- [x] aa4e57a Rationale for spatial/temporal scope selection
- [x] ff38f41 Create new section 3.6 Validation, building on content from 3.3 and 3.5. Discuss why this model is valid to answer the research question (and why maybe not)

### 4. Experimental setup
- [x] 2f3dcdb Move from Appendix D to Section 4 (to make the main text more readable on its own):
  * Overview of experimental design
  * Scenario selection rationale
  * Policy intervention choices
- Keep in appendix:
  * Detailed parameter tables
  * Technical implementation details

### 5. Results
- [x] f0c45cc Write clearer introduction paragraph, what will be answered were based on which experiment.
- [x] 8c1d725 Add overview table clearly linking which section answers which subquestion by which experiment examining which metrics.

### 7. Conclusions
- [x] 261efe2 Less summary, not per sub-question, more reflecting on the main question
- [x] 261efe2 Revisit societal/policy advice

### General
- [x] Explain concepts when first introduced rather than leaving details to appendices
- [x] Add clear definitions in main text for:
  * AV density and its implications 
  * Induced demand in context of AVs
  * Comfort factors and their role
- [x] a9b5f400 Update title and subtitle to be more reflective, objective and modest
- [x] 8f1d0410 Update abstract to represent updated article

@quaquel This a good interpretation of your feedback? Missing anything?

### Considered but rejected
A few feedback points were considered, but implemented differently than suggested due to other considerations.

1. Move temporal/spatial scope justification from 3.1 to Section 2 (wait for response email)
2. Move scenario and policy selection motivation to 2 (mail response)

1. and 2. both weren't moved, but explained better in place, with forward references to them. This was motivated by keeping the story as linearly readable as possible and not explaining things without proper context being present.

**Comment by EwoutH** [comment]
Title: Difficult to capture the full picture (does maybe show lack of focus in the study). Maybe:
- When do autonomous vehicles solve versus exacerbate different urban mobility problems?

It's nice high level and captures the broad goal, while leaving the details to the subquestions.

**Comment by quaquel** [comment]
I would replace versus with `or`: When do autonomous vehicles solve or exacerbate different urban mobility problems?

**Comment by EwoutH** [comment]
Agreed. I'm considering pairing it with this subtitle:

- A simulation study exploring modal shifts and system-level impacts in dense urban environments
